export const copy = {
  pl: {
    hello: "Cześć",
    subtitle: "Oto co dzieje się dziś w Campus Gym.",
    home: "Strona główna",
    schedule: "Terminarz",
    admin: "Panel administratora",
    upcoming: "Twój najbliższy trening",
    news: "Aktualności",
    seeSchedule: "Zobacz terminarz",
    week: "Tydzień",
    month: "Miesiąc",
    book: "Zapisz się",
    yourBookings: "Twoje zapisy",
    comments: "komentarze",
    welcome: "Dobrze Cię widzieć",
    loginText: "Zaloguj się, aby zarządzać swoimi treningami.",
    email: "Adres e-mail",
    password: "Hasło",
    forgot: "Nie pamiętasz hasła?",
    login: "Zaloguj się",
    register: "Utwórz konto",
    noAccount: "Nie masz jeszcze konta?",
    user: "Użytkownik",
    administrator: "Administrator",
    logout: "Wyloguj",
    profile: "Twój profil",
    brandKicker: "TWOJA SIŁOWNIA. TWÓJ CZAS.",
    brandTitle: "Miejsce na",
    brandAccent: "Twój ruch.",
    brandDescription:
      "Proste zapisy, przejrzysty grafik i społeczność, która motywuje Cię każdego dnia.",
    members: "aktywnych członków",
    openingHours: "godziny otwarcia",
  },
  en: {
    hello: "Hi",
    subtitle: "Here's what's happening today at Campus Gym.",
    home: "Home",
    schedule: "Schedule",
    admin: "Admin panel",
    upcoming: "Your next workout",
    news: "News & updates",
    seeSchedule: "View schedule",
    week: "Week",
    month: "Month",
    book: "Book workout",
    yourBookings: "Your bookings",
    comments: "comments",
    welcome: "Welcome back",
    loginText: "Sign in to manage your workouts.",
    email: "Email address",
    password: "Password",
    forgot: "Forgot password?",
    login: "Sign in",
    register: "Create account",
    noAccount: "Don't have an account?",
    user: "Member",
    administrator: "Administrator",
    logout: "Sign out",
    profile: "Your profile",
    brandKicker: "YOUR GYM. YOUR TIME.",
    brandTitle: "Make room for",
    brandAccent: "your move.",
    brandDescription:
      "Simple bookings, a clear schedule and a community that keeps you motivated every day.",
    members: "active members",
    openingHours: "opening hours",
  },
};
